### ISSUE TITLE
The message button does not work

### ISSUE THREAD

**Issue by OnLinuxPro** [FxllenCode/HWHelpNow#5]
Hi FxllenCode, I recently went in to check out the HWHelp now site and noticed that the message button doesn't work.

Steps to play:
 -Go to the page.
-Try to send a message.

**Comment by FxllenCode** [comment]
Hello @OnLinuxPro,

See:

> Closing:
> 
> ![tOn4F5NuWH](https://user-images.githubusercontent.com/40151425/102563214-a0f66200-408d-11eb-87f6-9ffa3789261d.gif)



#2

It's a weird issue, follow the steps of the gif and it should work.

**Comment by OnLinuxPro** [comment]
Oh, i think is that, thanks.

**Comment by OnLinuxPro** [comment]
Oh, i think is that, thanks.
